// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CRUD.Infraestrcture.Context;

public partial class alumnosContext : DbContext
{
    public alumnosContext(DbContextOptions<alumnosContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alumnos> Alumnos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_general_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Alumnos>(entity =>
        {
            entity.HasKey(e => e.Idalumnos).HasName("PRIMARY");

            entity.ToTable("alumnos");

            entity.Property(e => e.Idalumnos)
                .HasColumnType("int(11)")
                .HasColumnName("idalumnos");
            entity.Property(e => e.Apellidos)
                .HasMaxLength(45)
                .HasColumnName("apellidos");
            entity.Property(e => e.Edad)
                .HasMaxLength(45)
                .HasColumnName("edad");
            entity.Property(e => e.Fecha)
                .HasMaxLength(45)
                .HasColumnName("fecha");
            entity.Property(e => e.Nombres)
                .HasMaxLength(45)
                .HasColumnName("nombres");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}