// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using CRUD.Entidades;

namespace CRUD.Infraestrcture.Context;

public partial class rpgContext : DbContext
{
    public rpgContext(DbContextOptions<rpgContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Rankings> Rankings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Rankings>(entity =>
        {
            entity.HasKey(e => e.IdRanking).HasName("PRIMARY");

            entity.ToTable("rankings");

            entity.Property(e => e.IdRanking).HasColumnName("id_ranking");
            entity.Property(e => e.Puntaje)
                .HasPrecision(10, 2)
                .HasColumnName("puntaje");
            entity.Property(e => e.Ultimonivel).HasColumnName("ultimonivel");
            entity.Property(e => e.Usuario)
                .HasMaxLength(50)
                .HasColumnName("usuario");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}