// <auto-generated> Ajustado manualmente para representar la entidad Persona. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD.Entidades;

public partial class Persona
{
    public int IdPersona { get; set; }

    public string Nombres { get; set; }

    public string Apellido { get; set; }

    public int Edad { get; set; }

    public string Estado { get; set; }
}
