// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD.Entidades;

public partial class Alumnos
{
    public int Idalumnos { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Edad { get; set; }

    public string Fecha { get; set; }
}