// <auto-generated> Entidad Rankings para la tabla 'rankings'. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD.Entidades;

public partial class Rankings
{
    public int IdRanking { get; set; }

    public string Usuario { get; set; }

    public decimal Puntaje { get; set; }

    public int Ultimonivel { get; set; }
}
